import { useEffect, useMemo, useState } from 'react';
import Peer from 'peerjs';
import { makeId, pointKey, rankStudents, toResult, validateProgram } from './game';
import type { ClassSession, Command, CommandType, Direction, MatchState, StudentRecord } from './types';
import { useRealtimeMatch } from './useRealtimeMatch';
import './index.css';

const LABEL: Record<CommandType, string> = { forward: '앞으로 1칸', turnLeft: '왼쪽 90°', turnRight: '오른쪽 90°' };
const ARROW: Record<Direction, string> = { north: '↑', east: '→', south: '↓', west: '←' };
const shade = (i: number) => i ? 'coral' : 'mint';

function MazeBoard({ match }: { match: MatchState }) { return <div className="maze" role="grid" aria-label="7×7 기억의 미로">{Array.from({ length: 49 }, (_, index) => { const row = Math.floor(index / 7), col = index % 7, key = `${row},${col}`; return <div className="cell" role="gridcell" key={key}>{match.players.map((p, i) => pointKey(p.start) === key && <span key={`s${p.id}`} className={`marker start ${shade(i)}`}>출발</span>)}{match.players.map((p, i) => pointKey(p.goal) === key && <span key={`g${p.id}`} className={`marker goal ${shade(i)}`}>도착</span>)}<div className="pawns">{match.players.map((p, i) => pointKey(p.position) === key && <span key={p.id} className={`pawn ${shade(i)}`} aria-label={`${p.name}, ${p.direction}`}><b>{ARROW[p.direction]}</b><small>{p.name.slice(0, 2)}</small></span>)}</div></div>; })}</div>; }

function CommandPanel({ match, onRun }: { match: MatchState; onRun: (commands: Command[], useDouble: boolean) => void }) {
  const current = match.players.find(p => p.id === match.currentPlayerId)!;
  const [commands, setCommands] = useState<Command[]>([]), [selected, setSelected] = useState<string>(), [useDouble, setUseDouble] = useState(false);
  const check = validateProgram(commands, useDouble), max = useDouble ? 18 : 12;
  const add = (type: CommandType) => { if (commands.length >= max || (type === 'forward' && check.forwards >= check.required)) return; setCommands(items => [...items, { id: makeId('cmd'), type }]); };
  const move = (delta: number) => { const index = commands.findIndex(c => c.id === selected); if (index < 0 || index + delta < 0 || index + delta >= commands.length) return; const next = [...commands], [item] = next.splice(index, 1); next.splice(index + delta, 0, item); setCommands(next); };
  return <aside className="command-panel"><div className="panel-title"><div><span className="eyebrow">내 프로그램</span><h2>명령을 조립하세요</h2></div><b>{check.forwards} / {check.required}칸</b></div><div className="command-buttons"><button onClick={() => add('forward')}>↑ <span>앞으로 1칸</span></button><button onClick={() => add('turnLeft')}>↶ <span>왼쪽 회전</span></button><button onClick={() => add('turnRight')}>↷ <span>오른쪽 회전</span></button></div><ol className="command-list">{commands.length ? commands.map((command, index) => <li key={command.id} className={selected === command.id ? 'selected' : ''} onClick={() => setSelected(command.id)}><span>{index + 1}</span><b>{command.type === 'forward' ? '↑' : command.type === 'turnLeft' ? '↶' : '↷'} {LABEL[command.type]}</b></li>) : <li className="empty">명령 버튼을 눌러<br/>실행 순서를 만들어 보세요.</li>}</ol><div className="edit-row"><button onClick={() => move(-1)} disabled={!selected}>위로</button><button onClick={() => move(1)} disabled={!selected}>아래로</button><button onClick={() => setCommands(v => v.filter(c => c.id !== selected))} disabled={!selected}>선택 삭제</button><button onClick={() => { setCommands([]); setSelected(undefined); }}>전체 초기화</button></div><button className={`double ${useDouble ? 'active' : ''}`} disabled={current.doubleChancesRemaining < 1} onClick={() => { setUseDouble(v => !v); setCommands([]); }}>⚡ 더블찬스 <span>남은 {current.doubleChancesRemaining}회 · {useDouble ? '6칸 모드' : '켜기'}</span></button><p className={check.valid ? 'hint ok' : 'hint'}>{check.message}</p><button className="run" disabled={!check.valid} onClick={() => { onRun(commands, useDouble); setCommands([]); setSelected(undefined); setUseDouble(false); }}>▶ 프로그램 실행</button><details><summary>이번 턴 순서도</summary><div className="flow"><i>시작</i>{commands.map(c => <span className="flow-step" key={c.id}><em>↓</em><i>{LABEL[c.type]}</i></span>)}</div></details></aside>;
}

function StudentEntry({ onBack, createRoom, joinRoom, status }: { onBack:()=>void; createRoom:(n:string,c:string)=>void; joinRoom:(n:string,c:string)=>void; status:string }) {
  const [name,setName]=useState(''),[code,setCode]=useState(''); const ready=name.trim()&&code.trim().length>=4;
  return <main className="form-page"><button className="quiet back" onClick={onBack}>← 돌아가기</button><section className="form-card"><div className="brand"><span>迷</span><b>학생 입장</b></div><h1>친구와 미로 대결을 시작해요</h1><p>같은 경기 코드를 입력한 두 학생이 연결됩니다.</p><label>이름 또는 번호<input value={name} onChange={e=>setName(e.target.value.slice(0,20))} placeholder="예: 12번 김민준"/></label><label>경기 코드<input value={code} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9-]/g,''))} placeholder="예: MAZE-42"/></label><div className={`network-state ${status}`}>● {status==='connecting'?'연결 중':status==='error'?'연결 실패 · 코드를 확인하세요':'입장 준비'}</div><div className="split-actions"><button disabled={!ready} className="primary" onClick={()=>createRoom(name.trim(),code.trim())}>경기 만들기</button><button disabled={!ready} className="secondary" onClick={()=>joinRoom(name.trim(),code.trim())}>코드로 참가</button></div><small>경기를 만든 학생의 기기가 미로와 이동 결과를 안전하게 확인합니다.</small></section></main>;
}

const sessionKey='memory-maze:class-session:v1';
function Teacher({ onBack }: { onBack:()=>void }) {
  const [className,setClassName]=useState('5학년 2반'),[names,setNames]=useState('김민준\n이서연\n박지호\n최하은'),[session,setSession]=useState<ClassSession|null>(()=>{try{const raw=localStorage.getItem(sessionKey);return raw?JSON.parse(raw):null}catch{return null}}),[copied,setCopied]=useState(false);
  const students:StudentRecord[]=useMemo(()=>names.split(/[\n,]/).map(n=>n.trim()).filter(Boolean).map((name,i)=>({id:`student-${i+1}`,name})),[names]); const ranking=session?rankStudents(session):[];
  useEffect(()=>{if(!session)return; const peer=new Peer(`memory-maze-class-${session.code.toLowerCase()}`); peer.on('connection',connection=>connection.on('data',data=>{const result=data as ReturnType<typeof toResult>;if(!result?.matchId||result.classSessionId!==session.code)return;setSession(current=>{if(!current||current.results.some(item=>item.matchId===result.matchId))return current;const next={...current,results:[...current.results,result]};localStorage.setItem(sessionKey,JSON.stringify(next));return next})})); return()=>peer.destroy()},[session?.code]);
  const save=()=>{const next:ClassSession={id:makeId('class'),code:`M${Math.floor(1000+Math.random()*9000)}`,className,students,results:[],createdAt:Date.now()};localStorage.setItem(sessionKey,JSON.stringify(next));setSession(next)};
  const report=()=>`서비스명: 기억의 미로\n학급: ${session?.className}\n실행일: ${new Date().toLocaleDateString('ko-KR')}\n참가 학생 수: ${session?.students.length}\n완료 경기 수: ${session?.results.length}\n무효 경기 수: ${session?.results.filter(r=>r.finishReason==='invalid').length}\n\n순위 / 이름 / 경기 / 승 / 패 / 승점 / 승률 / 평균 턴 / 평균 충돌\n${ranking.map((r,i)=>`${i+1} / ${r.name} / ${r.games} / ${r.wins} / ${r.losses} / ${r.points} / ${Math.round(r.winRate*100)}% / ${r.averageTurns.toFixed(1)} / ${r.averageHits.toFixed(1)}`).join('\n')}`;
  return <main className="teacher"><header><button className="logo-button" onClick={onBack}>迷</button><div><span>교사 운영 페이지</span><h1>기억의 미로 수업 현황</h1></div></header>{!session?<section className="teacher-setup"><span className="eyebrow">학급 세션 만들기</span><h2>3분 안에 수업을 준비하세요</h2><div className="setup-grid"><label>학급명<input value={className} onChange={e=>setClassName(e.target.value)}/></label><label>학생 명단 <small>줄바꿈 또는 쉼표로 구분 · {students.length}명</small><textarea value={names} onChange={e=>setNames(e.target.value)}/></label></div><button className="primary" onClick={save} disabled={students.length<2||new Set(students.map(s=>s.name)).size!==students.length}>학급 세션 시작 →</button></section>:<><section className="teacher-head"><div><span className="eyebrow">{session.className}</span><h2>학급 코드 <b>{session.code}</b></h2><p>학생들이 이 코드를 경기 코드로 입력합니다.</p></div><div><strong>{session.students.length}</strong><span>등록 학생</span></div><div><strong>{session.results.length}</strong><span>완료 경기</span></div><button className="secondary" onClick={()=>{localStorage.removeItem(sessionKey);setSession(null)}}>새 세션</button></section><section className="teacher-grid"><article><header><h3>학생 경기 현황</h3><span>자동 저장됨</span></header><div className="student-status">{session.students.map((s,i)=><div key={s.id}><i className={i<2?'playing':''}/><b>{s.name}</b><span>{i<2?'경기 중':'대기'}</span></div>)}</div></article><article><header><h3>최종 순위</h3><button onClick={async()=>{await navigator.clipboard.writeText(report());setCopied(true)}}>{copied?'복사됨 ✓':'전체 결과 복사'}</button></header>{ranking.length?<table><thead><tr><th>순위</th><th>이름</th><th>경기</th><th>승점</th><th>승률</th></tr></thead><tbody>{ranking.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.name}</td><td>{r.games}</td><td>{r.points}</td><td>{Math.round(r.winRate*100)}%</td></tr>)}</tbody></table>:<div className="empty-results">경기 결과를 기다리고 있어요.<br/><small>같은 matchId는 한 번만 집계됩니다.</small></div>}</article></section></>}</main>;
}

function Home({go}:{go:(s:'intro'|'entry'|'teacher')=>void}) { return <main className="home"><nav><div className="brand"><span>迷</span><b>기억의 미로</b></div><button className="quiet" onClick={()=>go('intro')}>게임 방법</button></nav><section className="hero"><div className="hero-copy"><span className="eyebrow">1:1 알고리즘 대전</span><h1>보이지 않는 벽을<br/><em>기억</em>하고 탈출하라!</h1><p>이동과 회전 명령을 순서대로 조립해 상대보다 먼저 목적지에 도착하세요.</p><div><button className="primary" onClick={()=>go('entry')}>학생으로 시작 <b>→</b></button><button className="secondary" onClick={()=>go('teacher')}>교사로 시작</button></div></div><div className="hero-maze" aria-hidden><div className="mini-grid">{Array.from({length:25},(_,i)=><i key={i}>{i===0?'🧑‍🚀':i===24?'🏁':''}</i>)}</div><span className="memory-card">벽은 보이지 않아요<br/><b>부딪힌 곳을 기억!</b></span></div></section><footer><span>위치와 방향을 생각해요</span><span>명령을 순서대로 조립해요</span><span>결과를 보고 다시 고쳐요</span></footer></main>; }

export default function App() {
  const net=useRealtimeMatch(),[screen,setScreen]=useState<'home'|'intro'|'entry'|'game'|'teacher'>(()=>sessionStorage.getItem('memory-maze:active')?'game':'home'),[message,setMessage]=useState('현재 위치와 방향을 보고 명령을 조립하세요.'); const match=net.match;
  useEffect(()=>{if(match?.phase!=='completed')return; const result=toResult(match),raw=localStorage.getItem(sessionKey);if(raw){try{const session=JSON.parse(raw) as ClassSession;if(!session.results.some(r=>r.matchId===match.matchId)){session.results.push(result);localStorage.setItem(sessionKey,JSON.stringify(session));}}catch{}} if(net.role!=='demo'&&sessionStorage.getItem(`memory-maze:sent:${match.matchId}`)!=='1'){localStorage.setItem('memory-maze:pending-result',JSON.stringify(result));const peer=new Peer();peer.on('open',()=>{const connection=peer.connect(`memory-maze-class-${match.classSessionId.toLowerCase()}`,{reliable:true});connection.on('open',()=>{connection.send(result);sessionStorage.setItem(`memory-maze:sent:${match.matchId}`,'1');localStorage.removeItem('memory-maze:pending-result');setTimeout(()=>peer.destroy(),300)})});setTimeout(()=>peer.destroy(),5000);return()=>peer.destroy()}},[match?.phase,match?.matchId]);
  const current=match?.players.find(p=>p.id===match.currentPlayerId), myTurn=net.role==='demo'||net.localPlayerId===match?.currentPlayerId, last=match?.logs.at(-1);
  useEffect(()=>{if(!last||!match)return; const actor=match.players.find(p=>p.id===last.playerId)!; setMessage(last.won?`${actor.name} 도착! 미로를 탈출했어요.`:last.collision?`${(last.failedCommandIndex??0)+1}번째 명령에서 ${last.collisionKind==='boundary'?'미로 밖':'숨겨진 벽'}에 막혔어요. 출발점으로 돌아갑니다.`:`${last.moved}칸 이동 성공! 이제 상대 차례예요.`)},[last?.id]);
  if(screen==='home')return <Home go={setScreen}/>;
  if(screen==='entry')return <StudentEntry onBack={()=>setScreen('home')} status={net.status} createRoom={(n,c)=>{net.createRoom(n,c);setScreen('game')}} joinRoom={(n,c)=>{net.joinRoom(n,c);setScreen('game')}}/>;
  if(screen==='teacher')return <Teacher onBack={()=>setScreen('home')}/>;
  if(screen==='intro')return <main className="intro"><button className="quiet back" onClick={()=>setScreen('home')}>← 돌아가기</button><section><span className="eyebrow">30초 게임 방법</span><h1>생각하고, 조립하고, 실행!</h1><div className="rule-grid"><article><b>01</b><span>▦</span><h2>벽은 보이지 않아요</h2><p>부딪힌 위치를 기억해 다음 길을 찾아요.</p></article><article><b>02</b><span>🧩</span><h2>명령을 조립해요</h2><p>앞으로 3칸과 회전을 순서대로 놓아요.</p></article><article><b>03</b><span>↺</span><h2>실행하고 고쳐요</h2><p>벽에 막히면 출발점에서 다시 디버깅!</p></article></div><button className="primary" onClick={()=>{net.startDemo();setScreen('game')}}>연습 경기 시작 →</button></section></main>;
  if(!match)return <main className="form-page"><section className="form-card"><h1>경기를 복구하는 중이에요</h1><p>연결할 수 없다면 입장 화면에서 다시 시도해 주세요.</p><button className="primary" onClick={()=>setScreen('entry')}>입장 화면으로</button></section></main>;
  const run=(commands:Command[],useDouble:boolean)=>{net.submit(commands,useDouble);setMessage('프로그램을 실행하고 있어요…')};
  return <main className="game"><header><button className="logo-button" onClick={()=>{net.disconnect();setScreen('home')}}>迷</button><div><span>{net.role==='demo'?'연습 경기':`경기 코드 · ${net.roomCode}`}</span><h1><b>{match.turnNumber}턴</b> · {match.phase==='completed'?'경기 종료':`${current?.name} 차례`}</h1></div><div className={`connection ${net.status}`}><i/> {net.status==='connected'?'연결됨':net.status==='waiting'?'상대 기다리는 중':net.status==='reconnecting'?'연결 복구 중':'오프라인'}</div></header><div className="game-layout"><aside className="players">{match.players.map((p,i)=><article key={p.id} className={`${shade(i)} ${p.id===match.currentPlayerId?'current':''}`}><span>{net.role==='demo'?(i?'상대':'나'):(p.id===net.localPlayerId?'나':'상대')}</span><h2>{p.name}</h2><p>위치 {p.position.col+1}, {p.position.row+1} · 방향 {ARROW[p.direction]}</p><div>더블찬스 <b>{'⚡'.repeat(p.doubleChancesRemaining)}{'○'.repeat(2-p.doubleChancesRemaining)}</b></div></article>)}<div className="memory-tip"><b>기억 수첩</b><p>벽의 위치는 표시되지 않아요. 어느 명령에서 멈췄는지 기억하세요.</p></div></aside><section className="board-area"><div className="turn-banner"><i>{current?ARROW[current.direction]:'·'}</i><div><b>{match.phase==='completed'?`${current?.name} 승리!`:myTurn?'내 차례 · 명령을 조립하세요':`${current?.name}의 차례`}</b><span>{message}</span></div></div><MazeBoard match={match}/><p className="secret-note">눈에 보이지 않는 32개의 벽이 숨어 있어요</p></section>{match.phase==='completed'?<aside className="command-panel result-card"><span>🏆</span><h2>{current?.name} 승리!</h2><p>{match.turnNumber}턴의 실행 기록을 살펴보며 다음 명령을 생각해 보세요.</p><div className="review-box">어떤 명령에서 예상과 다른 결과가 나왔나요?<br/>회전 뒤의 방향을 정확히 생각했나요?</div><button className="primary" onClick={()=>{net.startDemo();setMessage('새 미로가 준비됐어요.')}}>다시 경기하기</button></aside>:myTurn?<CommandPanel key={match.turnNumber} match={match} onRun={run}/>:<aside className="command-panel waiting-card"><span>◌</span><h2>상대 차례예요</h2><p>상대의 프로그램 실행 결과를 보며 숨겨진 벽을 추리해 보세요.</p></aside>}</div></main>;
}
