import { useEffect, useMemo, useRef, useState } from 'react';
import Peer from 'peerjs';
import QRCode from 'qrcode';
import { createMatch, executeProgram, hasWall, inBounds, makeId, pointKey, rankStudents, stepFrom, toResult, turn, validateProgram } from './game';
import type { ClassSession, Command, CommandType, Direction, MatchResult, MatchState, Point, StudentRecord } from './types';
import './index.css';

const IMG='/assets/images/', AUDIO='/assets/audio/';
const LABEL:Record<CommandType,string>={forward:'앞으로 1칸',turnLeft:'왼쪽 90°',turnRight:'오른쪽 90°'};
const ARROW:Record<Direction,string>={north:'↑',east:'→',south:'↓',west:'←'};
const SESSION_KEY='memory-maze:teacher-game:v3', PENDING_KEY='memory-maze:pending-results:v3';
type Screen='home'|'venue'|'practice'|'teacher';
type VenueStatus='available'|'occupied'|'result_pending'|'closed';
type TeacherGame=ClassSession&{venueCount:number;statuses:Record<number,VenueStatus>;ended:boolean};
type VenueEvent={type:'occupied'|'available'|'result';venue:number;result?:MatchResult};
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const readTeacher=():TeacherGame|null=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}};

function SoundButton(){const [muted,setMuted]=useState(false);useEffect(()=>{const main=new Audio(`${AUDIO}bgm_main_memory_mazy_loop.mp3`);main.loop=true;main.volume=.18;if(!muted){const start=()=>{void main.play();removeEventListener('pointerdown',start)};addEventListener('pointerdown',start,{once:true});return()=>{removeEventListener('pointerdown',start);main.pause()}}},[muted]);return <button className="icon-btn" onClick={()=>setMuted(v=>!v)} aria-label={muted?'소리 켜기':'음소거'}>{muted?'🔇':'🔊'}</button>}

function RulesModal({close,startPractice}:{close:()=>void;startPractice:()=>void}){const [slide,setSlide]=useState(0);const slides=[
  <div className="rule-slide"><span className="slide-kicker">1 / 4 · 게임의 목적</span><h2>숨겨진 벽을 기억하고<br/>먼저 도착하세요</h2><div className="goal-visual"><img src={`${IMG}pawn_player_mint.png`}/><span>명령 조립 → 실행 → 확인 → 수정</span><img src={`${IMG}marker_goa_flag.png`}/></div><p>두 플레이어는 서로 다른 출발점에서 시작합니다. 이동과 회전 명령을 조립해 자신의 색과 같은 도착점에 먼저 닿으면 승리합니다.</p></div>,
  <div className="rule-slide"><span className="slide-kicker">2 / 4 · 실제 게임 방법</span><h2>한 태블릿에서 번갈아 실행해요</h2><div className="how-layout"><div className="tiny-board">{Array.from({length:49},(_,i)=><i key={i}>{i===0?'●':i===6?'●':i===42||i===48?'◆':''}</i>)}</div><ol><li><b>① 현재 차례 확인</b><span>플레이어 색과 말의 방향을 확인합니다.</span></li><li><b>② 명령 조립</b><span>일반 턴은 전진 3번, 더블찬스는 6번입니다.</span></li><li><b>③ 실행 결과 관찰</b><span>회전과 이동을 보고 숨겨진 벽을 기억합니다.</span></li><li><b>④ 수정하고 재도전</b><span>벽에 부딪히면 출발점으로 돌아갑니다.</span></li></ol></div></div>,
  <div className="rule-slide"><span className="slide-kicker">3 / 4 · 교사 운영</span><h2>게임 사전 설정부터 종료까지</h2><div className="teacher-steps"><article><b>1</b><span>학생 명단과 경기장 수를 설정하고 4자리 학급 코드를 기억합니다.</span></article><article><b>2</b><span>경기장별 QR 코드 또는 링크를 각 태블릿에서 엽니다.</span></article><article><b>3</b><span>경기장에서 두 학생을 선택해 게임을 시작합니다.</span></article><article><b>4</b><span>모든 대결이 끝나면 게임 종료를 눌러 최종 순위를 공개합니다.</span></article></div></div>,
  <div className="rule-slide youtube-slide"><span className="slide-kicker">4 / 4 · 더 알아보기</span><div className="youtube-mark">▶</div><h2>원작 규칙이 궁금한가요?</h2><p>유튜브에서 <b>“더 지니어스 기억의 미로 규칙”</b>을 검색해 보세요.</p><button className="primary" onClick={startPractice}>연습 경기 시작</button></div>
];return <div className="modal" role="dialog" aria-modal="true"><section className="rules-modal"><header><div><img src={`${IMG}icon_logo_maze_mark.png`}/><b>기억의 미로 · 게임 방법</b></div><button onClick={close}>✕ 닫기</button></header><div className="rules-body">{slides[slide]}</div><footer><button onClick={()=>setSlide(v=>Math.max(0,v-1))} disabled={slide===0}>← 이전</button><div>{slides.map((_,i)=><button key={i} className={i===slide?'active':''} onClick={()=>setSlide(i)} aria-label={`${i+1}번째 슬라이드`}/>)}</div>{slide<3?<button className="primary" onClick={()=>setSlide(v=>v+1)}>다음 →</button>:<button className="primary" onClick={close}>확인</button>}</footer></section></div>}

function Home({go}:{go:(screen:Screen)=>void}){const [rules,setRules]=useState(false);return <main className="home"><nav><div className="brand"><img src={`${IMG}icon_logo_maze_mark.png`}/><b>기억의 미로</b></div><SoundButton/></nav><section className="hero"><div className="hero-copy"><span className="hero-kicker">더 지니어스 한 학급 놀이</span><h1>기억의 미로</h1><p><b>5학년 실과</b> 컴퓨터와 문제해결<br/><b>4학년 수학</b> 평면도형의 이동</p><div className="home-actions"><button className="primary" onClick={()=>go('teacher')}>교사로 시작</button><button className="secondary" onClick={()=>setRules(true)}>게임 방법</button><button className="secondary practice-btn" onClick={()=>go('practice')}>연습 경기</button></div></div></section>{rules&&<RulesModal close={()=>setRules(false)} startPractice={()=>{setRules(false);go('practice')}}/>}</main>}

function CommandPanel({match,disabled,onRun}:{match:MatchState;disabled:boolean;onRun:(commands:Command[],useDouble:boolean)=>void}){const current=match.players.find(p=>p.id===match.currentPlayerId)!;const [commands,setCommands]=useState<Command[]>([]),[selected,setSelected]=useState<string>(),[double,setDouble]=useState(false);const check=validateProgram(commands,double),limit=double?18:12;const add=(type:CommandType)=>{if(disabled||commands.length>=limit||(type==='forward'&&check.forwards>=check.required))return;setCommands(v=>[...v,{id:makeId('cmd'),type}])};const move=(delta:number)=>{const index=commands.findIndex(c=>c.id===selected);if(index<0||index+delta<0||index+delta>=commands.length)return;const next=[...commands],[item]=next.splice(index,1);next.splice(index+delta,0,item);setCommands(next)};return <aside className="command-panel"><div className="panel-title"><div><small>이번 턴 프로그램</small><h2>명령을 조립하세요</h2></div><b>{check.forwards}/{check.required}칸</b></div><div className="command-buttons"><button disabled={disabled} onClick={()=>add('forward')}>↑<span>앞으로 1칸</span></button><button disabled={disabled} onClick={()=>add('turnLeft')}>↶<span>왼쪽 회전</span></button><button disabled={disabled} onClick={()=>add('turnRight')}>↷<span>오른쪽 회전</span></button></div><ol className="command-list">{commands.length?commands.map((c,i)=><li key={c.id} onClick={()=>setSelected(c.id)} className={selected===c.id?'selected':''}><span>{i+1}</span><b>{c.type==='forward'?'↑':c.type==='turnLeft'?'↶':'↷'} {LABEL[c.type]}</b></li>):<li className="empty">명령을 눌러<br/>실행 순서를 만드세요</li>}</ol><div className="edit-row"><button onClick={()=>move(-1)} disabled={!selected||disabled}>위로</button><button onClick={()=>move(1)} disabled={!selected||disabled}>아래로</button><button onClick={()=>setCommands(v=>v.filter(c=>c.id!==selected))} disabled={!selected||disabled}>선택 삭제</button><button onClick={()=>setCommands([])} disabled={disabled}>전체 초기화</button></div><button className={`double ${double?'active':''}`} disabled={disabled||current.doubleChancesRemaining<1} onClick={()=>{setDouble(v=>!v);setCommands([])}}><img src={`${IMG}icon_double_chance.png`}/>더블찬스 <span>남은 {current.doubleChancesRemaining}회</span></button><p className={check.valid?'hint ok':'hint'}>{disabled?'프로그램을 실행하고 있어요.':check.message}</p><button className="run" disabled={disabled||!check.valid} onClick={()=>{onRun(commands,double);setCommands([]);setSelected(undefined);setDouble(false)}}>▶ 프로그램 실행</button></aside>}

function MazeBoard({match,visual,bump}:{match:MatchState;visual:{playerId:string;position:Point;direction:Direction}|null;bump:boolean}){return <div className="maze" role="grid" aria-label="7×7 기억의 미로">{Array.from({length:49},(_,index)=>{const row=Math.floor(index/7),col=index%7,key=`${row},${col}`;return <div className="cell" role="gridcell" key={key}>{match.players.map((p,i)=>pointKey(p.start)===key&&<span key={`s${p.id}`} className={`start-zone p${i}`}>출발</span>)}{match.players.map((p,i)=>pointKey(p.goal)===key&&<span key={`g${p.id}`} className={`goal-zone p${i}`}><img src={`${IMG}marker_goa_flag.png`}/>도착</span>)}<div className="pawns">{match.players.map((p,i)=>{const pos=visual?.playerId===p.id?visual.position:p.position,dir=visual?.playerId===p.id?visual.direction:p.direction;if(pointKey(pos)!==key)return null;return <div key={p.id} className={`pawn-wrap p${i} ${bump&&visual?.playerId===p.id?'bump':''}`}><img className="pawn-img" src={`${IMG}${i?'pawn_player_coral.png':'pawn_player_mint.png'}`} style={{transform:`rotate(${({north:0,east:90,south:180,west:270} as Record<Direction,number>)[dir]}deg)`}}/><b>{ARROW[dir]}</b>{bump&&<img className="collision" src={`${IMG}effect_wall_collision.png`}/>}</div>})}</div></div>})}</div>}

async function sendVenueEvent(code:string,event:VenueEvent){const queue:VenueEvent[]=JSON.parse(localStorage.getItem(PENDING_KEY)||'[]');if(event.type==='result'&&!queue.some(item=>item.result?.matchId===event.result?.matchId)){queue.push(event);localStorage.setItem(PENDING_KEY,JSON.stringify(queue))}return new Promise<boolean>(resolve=>{const peer=new Peer(),timer=setTimeout(()=>{peer.destroy();resolve(false)},4500);peer.on('open',()=>{const connection=peer.connect(`memory-maze-class-${code}`,{reliable:true});connection.on('open',()=>connection.send(event));connection.on('data',data=>{if((data as {ok?:boolean}).ok){clearTimeout(timer);if(event.type==='result'){const left=(JSON.parse(localStorage.getItem(PENDING_KEY)||'[]') as VenueEvent[]).filter(item=>item.result?.matchId!==event.result?.matchId);localStorage.setItem(PENDING_KEY,JSON.stringify(left))}peer.destroy();resolve(true)}})});peer.on('error',()=>{clearTimeout(timer);peer.destroy();resolve(false)})})}

function GameScreen({practice,venue,code,roster,goHome}:{practice:boolean;venue:number;code:string;roster:string[];goHome:()=>void}){const [phase,setPhase]=useState<'select'|'play'|'closed'>('select'),[names,setNames]=useState<[string,string]>([roster[0]||'민준',roster[1]||'서연']),[match,setMatch]=useState<MatchState|null>(null),[visual,setVisual]=useState<{playerId:string;position:Point;direction:Direction}|null>(null),[bump,setBump]=useState(false),[animating,setAnimating]=useState(false),[message,setMessage]=useState('현재 차례의 플레이어가 명령을 조립하세요.');
 useEffect(()=>{if(practice)return;const peer=new Peer(`memory-maze-venue-${code}-${venue}`);peer.on('connection',conn=>conn.on('data',data=>{if((data as {type?:string}).type==='game-ended'){setPhase('closed');setMatch(null)}}));return()=>peer.destroy()},[practice,code,venue]);
 useEffect(()=>{if(practice)return;const retry=()=>{const pending=JSON.parse(localStorage.getItem(PENDING_KEY)||'[]') as VenueEvent[];for(const event of pending)void sendVenueEvent(code,event)};retry();const timer=setInterval(retry,8000);return()=>clearInterval(timer)},[practice,code]);
 const start=async()=>{if(names[0]===names[1])return;const next=createMatch(names,`${code}-${venue}-${Date.now()}`,code);setMatch(next);setPhase('play');if(!practice)void sendVenueEvent(code,{type:'occupied',venue})};
 const run=async(commands:Command[],useDouble:boolean)=>{if(!match||animating)return;setAnimating(true);const actor=match.players.find(p=>p.id===match.currentPlayerId)!;let position={...actor.position},direction=actor.direction,hit=false;setVisual({playerId:actor.id,position,direction});for(const command of commands){await wait(420);if(command.type==='turnLeft')direction=turn(direction,'left');else if(command.type==='turnRight')direction=turn(direction,'right');else{const next=stepFrom(position,direction);if(!inBounds(next)||hasWall(match.walls,position,next)){hit=true;setBump(true);setMessage('쿵! 숨겨진 벽에 부딪혔어요. 어느 명령이었는지 기억하세요.');await wait(650);setBump(false);position={...actor.start};setVisual({playerId:actor.id,position,direction});await wait(350);break}position=next}setVisual({playerId:actor.id,position,direction})}await wait(250);const next=executeProgram(match,actor.id,commands,useDouble,makeId('action'));setMatch(next);setVisual(null);setAnimating(false);const log=next.logs.at(-1)!;setMessage(log.won?`${actor.name} 승리! 목적지에 도착했습니다.`:hit?'출발점으로 돌아왔어요. 다음 차례에 명령을 고쳐 보세요.':`${log.moved}칸 이동했습니다. 다음 플레이어 차례입니다.`);if(next.phase==='completed'&&!practice){const result=toResult(next);const ok=await sendVenueEvent(code,{type:'result',venue,result});setMessage(ok?`${actor.name} 승리! 결과가 교사에게 전송됐습니다.`:`${actor.name} 승리! 결과를 기기에 보관했습니다. 연결되면 다시 전송합니다.`);void sendVenueEvent(code,{type:'available',venue})}};
 if(phase==='closed')return <main className="closed-screen"><img src={`${IMG}icon_victory_trophy.png`}/><h1>전체 게임이 종료되었습니다.</h1><p>교사가 최종 순위를 발표합니다.</p></main>;
 if(phase==='select')return <main className="venue-select"><header><div className="brand"><img src={`${IMG}icon_logo_maze_mark.png`}/><b>{practice?'연습 경기':`${venue}번 경기장`}</b></div>{practice&&<button className="secondary" onClick={goHome}>메인화면</button>}</header><section><span>플레이어 선택</span><h1>대결할 두 학생을 선택하세요</h1><div><label>첫 번째 플레이어<select value={names[0]} onChange={e=>setNames([e.target.value,names[1]])}>{roster.map(n=><option key={n}>{n}</option>)}</select></label><b>VS</b><label>두 번째 플레이어<select value={names[1]} onChange={e=>setNames([names[0],e.target.value])}>{roster.map(n=><option key={n}>{n}</option>)}</select></label></div>{names[0]===names[1]&&<p className="error">서로 다른 두 학생을 선택해 주세요.</p>}<button className="primary" disabled={names[0]===names[1]} onClick={start}>게임 시작 →</button></section></main>;
 if(!match)return null;const current=match.players.find(p=>p.id===match.currentPlayerId)!;return <main className="game"><header><button className="logo-button"><img src={`${IMG}icon_logo_maze_mark.png`}/></button><div><span>{practice?'연습 경기':`${venue}번 경기장`}</span><h1><b>{match.turnNumber}턴</b> · {match.phase==='completed'?'경기 종료':`${current.name} 차례`}</h1></div>{practice&&<button className="secondary" onClick={goHome}>메인화면으로</button>}</header><div className="game-layout"><aside className="players">{match.players.map((p,i)=><article key={p.id} className={`p${i} ${p.id===current.id?'current':''}`}><div><img src={`${IMG}${i?'pawn_player_coral.png':'pawn_player_mint.png'}`}/><span><small>{i+1}P</small><h2>{p.name}</h2></span></div><p>전적 <b>{p.turns}턴 · 충돌 {p.wallHits}회</b></p><p>더블찬스 <b>{'⚡'.repeat(p.doubleChancesRemaining)}{'○'.repeat(2-p.doubleChancesRemaining)}</b></p></article>)}<div className="quick-rules"><h3>게임 목표</h3><p>내 말과 같은 색의 <b>도착점</b>에 먼저 도착하세요.</p><h3>게임 방법</h3><p>전진 3번과 회전 명령을 순서대로 조립합니다. 벽에 부딪히면 출발점으로 돌아갑니다.</p></div><div className="memory-tip"><img src={`${IMG}icon_memory_note.png`}/><div><b>기억 수첩</b><p>어느 명령에서 멈췄는지 기억하세요.</p></div></div></aside><section className="board-area"><div className="turn-banner"><i className={current.id==='player-a'?'mint':'coral'}>{ARROW[visual?.playerId===current.id?visual.direction:current.direction]}</i><div><b>{match.phase==='completed'?`${current.name} 승리!`:`${current.name} 차례`}</b><span>{message}</span></div></div><MazeBoard match={match} visual={visual} bump={bump}/><p className="secret-note">보이지 않는 벽 32개가 숨어 있습니다</p></section>{match.phase==='completed'?<aside className="command-panel result-card"><img src={`${IMG}icon_victory_trophy.png`}/><h2>{current.name} 승리!</h2><p>명령의 순서를 떠올리며 결정적 순간을 복기해 보세요.</p><button className="primary" onClick={()=>{setPhase('select');setMatch(null)}}>다음 경기</button></aside>:<CommandPanel key={match.turnNumber} match={match} disabled={animating} onRun={run}/>}</div></main>}

function VenueCard({venue,code,roster,status}:{venue:number;code:string;roster:string[];status:VenueStatus}){const [qr,setQr]=useState('');const url=useMemo(()=>{const target=new URL(location.href);target.search='';target.searchParams.set('venue',String(venue));target.searchParams.set('class',code);target.searchParams.set('players',btoa(unescape(encodeURIComponent(JSON.stringify(roster)))));return target.toString()},[venue,code,roster]);useEffect(()=>{QRCode.toDataURL(url,{width:220,margin:1,color:{dark:'#26233c',light:'#fffdf7'}}).then(setQr)},[url]);return <article className="venue-card"><div>{qr&&<img src={qr}/>}<span><b>{venue}번 경기장</b><small className={status}>{status==='available'?'이용 가능':status==='occupied'?'경기 중':status==='closed'?'종료':'결과 전송 중'}</small></span></div><button onClick={()=>void navigator.clipboard.writeText(url)}>경기장 링크 복사</button></article>}

function Teacher({goHome}:{goHome:()=>void}){const [game,setGame]=useState<TeacherGame|null>(readTeacher),[names,setNames]=useState('김민준\n이서연\n박지호\n최하은'),[venues,setVenues]=useState(4),[recover,setRecover]=useState(''),[confirm,setConfirm]=useState(false),[final,setFinal]=useState(false);const students=useMemo(()=>names.split(/[\n,]/).map(n=>n.trim()).filter(Boolean).map((name,i)=>({id:`student-${i}`,name})),[names]);const save=(next:TeacherGame)=>{localStorage.setItem(SESSION_KEY,JSON.stringify(next));setGame(next)};
 useEffect(()=>{
  if(!game||game.ended)return;
  const peer=new Peer(`memory-maze-class-${game.code}`);
  peer.on('connection',conn=>conn.on('data',data=>{
   const event=data as VenueEvent,current=readTeacher()||game;
   let results=current.results;
   if(event.type==='result'&&event.result&&!results.some(item=>item.matchId===event.result?.matchId))results=[...results,event.result];
   const status:VenueStatus=event.type==='occupied'?'occupied':event.type==='available'||event.type==='result'?'available':current.statuses[event.venue];
   save({...current,results,statuses:{...current.statuses,[event.venue]:status}});
   conn.send({ok:true});
  }));
  return()=>peer.destroy();
 },[game?.code,game?.ended]);
 const create=()=>{const code=String(Math.floor(1000+Math.random()*9000)),statuses=Object.fromEntries(Array.from({length:venues},(_,i)=>[i+1,'available'])) as Record<number,VenueStatus>;save({id:makeId('class'),code,className:'기억의 미로',students,results:[],createdAt:Date.now(),venueCount:venues,statuses,ended:false})};const ranking=game?rankStudents(game):[];const report=()=>['순위\t이름\t경기\t승\t패\t승점\t승률\t평균 턴\t평균 충돌',...ranking.map((r,i)=>`${i+1}\t${r.name}\t${r.games}\t${r.wins}\t${r.losses}\t${r.points}\t${Math.round(r.winRate*100)}%\t${r.averageTurns.toFixed(1)}\t${r.averageHits.toFixed(1)}`)].join('\n');const finish=()=>{if(!game)return;const next={...game,ended:true,statuses:Object.fromEntries(Object.keys(game.statuses).map(k=>[k,'closed'])) as Record<number,VenueStatus>};save(next);setConfirm(false);setFinal(true);const bgm=new Audio(`${AUDIO}bgm_result_maze_reveal.mp3`);bgm.volume=.55;void bgm.play();for(let venue=1;venue<=game.venueCount;venue++){const peer=new Peer();peer.on('open',()=>{const conn=peer.connect(`memory-maze-venue-${game.code}-${venue}`);conn.on('open',()=>{conn.send({type:'game-ended'});setTimeout(()=>peer.destroy(),250)})});setTimeout(()=>peer.destroy(),3000)}};
 if(final&&game)return <main className="final-ranking"><img className="confetti" src={`${IMG}effect_goal_confetti.png`}/><img className="trophy" src={`${IMG}icon_victory_trophy.png`}/><span>전체 게임 종료</span><h1>최종 순위</h1><div className="podium">{ranking.slice(0,3).map((r,i)=><article key={r.id} className={`rank-${i+1}`}><b>{i+1}위</b><h2>{r.name}</h2><p>{r.points}점 · {r.wins}승</p></article>)}</div><button className="primary" onClick={()=>void navigator.clipboard.writeText(report())}>게임 결과 복사하기</button><p>버튼을 누른 뒤 한셀 또는 엑셀에서 붙여넣으면 표로 저장할 수 있습니다.</p></main>;
 if(!game)return <main className="teacher"><header><button className="logo-button" onClick={goHome}><img src={`${IMG}icon_logo_maze_mark.png`}/></button><div><span>교사 운영 페이지</span><h1>게임 사전 설정</h1></div></header><section className="teacher-setup"><h2>게임 사전 설정</h2><label>학생 명단 <small>줄바꿈 또는 쉼표로 구분 · {students.length}명</small><textarea value={names} onChange={e=>setNames(e.target.value)}/></label><label>운영할 경기장 수<input type="number" min="1" max="12" value={venues} onChange={e=>setVenues(Math.max(1,Math.min(12,Number(e.target.value))))}/></label><button className="primary" disabled={students.length<2||new Set(students.map(s=>s.name)).size!==students.length} onClick={create}>게임 만들기</button><div className="recover"><b>기존 게임 재접속</b><div><input inputMode="numeric" maxLength={4} placeholder="4자리 학급 코드" value={recover} onChange={e=>setRecover(e.target.value.replace(/\D/g,'').slice(0,4))}/><button onClick={()=>{const saved=readTeacher();if(saved?.code===recover)setGame(saved)}}>재접속</button></div></div></section></main>;
 return <main className="teacher"><header><button className="logo-button" onClick={goHome}><img src={`${IMG}icon_logo_maze_mark.png`}/></button><div><span>교사 운영 페이지</span><h1>기억의 미로 게임</h1></div><button className="danger-btn" onClick={()=>setConfirm(true)}>게임 종료</button></header><section className="class-code"><div><span>학급 코드</span><strong>{game.code}</strong></div><p>학급 코드를 기억해 주세요. 혹시라도 교사 운영 페이지에서 나갔을 경우 학급 코드를 입력하시면 재접속하실 수 있습니다.</p></section><div className="teacher-grid"><section><header><h2>경기장</h2><span>{game.venueCount}개 운영</span></header><div className="venues">{Array.from({length:game.venueCount},(_,i)=><VenueCard key={i} venue={i+1} code={game.code} roster={game.students.map(s=>s.name)} status={game.statuses[i+1]}/>)}</div></section><section><header><h2>현재 순위</h2><span>{game.results.length}경기 완료</span></header><table><thead><tr><th>순위</th><th>이름</th><th>경기</th><th>승</th><th>승점</th></tr></thead><tbody>{ranking.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.name}</td><td>{r.games}</td><td>{r.wins}</td><td>{r.points}</td></tr>)}</tbody></table></section></div>{confirm&&<div className="modal"><section className="confirm"><h2>전체 경기를 종료하시겠습니까?</h2><p>운영 중인 게임은 전적에 반영되지 않습니다.</p><div><button onClick={()=>setConfirm(false)}>취소</button><button className="danger-btn" onClick={finish}>확인하고 종료</button></div></section></div>}</main>}

export default function App(){const params=new URLSearchParams(location.search),venue=Number(params.get('venue')||0),code=params.get('class')||'',encoded=params.get('players');let roster=['민준','서연','지호','하은'];try{if(encoded)roster=JSON.parse(decodeURIComponent(escape(atob(encoded))))}catch{}const [screen,setScreen]=useState<Screen>(venue?'venue':'home');if(screen==='home')return <Home go={setScreen}/>;if(screen==='teacher')return <Teacher goHome={()=>setScreen('home')}/>;return <GameScreen practice={screen==='practice'} venue={venue||0} code={code||'0000'} roster={roster} goHome={()=>{history.replaceState(null,'',location.pathname);setScreen('home')}}/>}
