import { useEffect, useState } from 'react';

const IMG='/assets/images/',AUDIO='/assets/audio/';
export type Screen='home'|'venue'|'practice'|'teacher';

function SoundButton(){const [muted,setMuted]=useState(false);useEffect(()=>{const main=new Audio(`${AUDIO}bgm_main_memory_mazy_loop.mp3`);main.loop=true;main.volume=.18;if(!muted){const start=()=>{void main.play();removeEventListener('pointerdown',start)};addEventListener('pointerdown',start,{once:true});return()=>{removeEventListener('pointerdown',start);main.pause()}}},[muted]);return <button className="icon-btn" onClick={()=>setMuted(v=>!v)} aria-label={muted?'소리 켜기':'음소거'}>{muted?'🔇':'🔊'}</button>}

function RulesModal({close,startPractice}:{close:()=>void;startPractice:()=>void}){const [slide,setSlide]=useState(0);const slides=[
  <div className="rule-slide"><span className="slide-kicker">1 / 4 · 게임의 목적</span><h2>숨겨진 벽을 기억하고<br/>먼저 도착하세요</h2><div className="goal-visual"><img src={`${IMG}pawn_player_mint.png`}/><span>명령 조립 → 실행 → 확인 → 수정</span><img src={`${IMG}marker_goa_flag.png`}/></div><p>두 플레이어는 서로 다른 출발점에서 시작합니다. 이동과 회전 명령을 조립해 자신의 색과 같은 도착점에 먼저 닿으면 승리합니다.</p></div>,
  <div className="rule-slide"><span className="slide-kicker">2 / 4 · 실제 게임 방법</span><h2>한 태블릿에서 번갈아 실행해요</h2><div className="how-layout"><div className="tiny-board">{Array.from({length:49},(_,i)=><i key={i}>{i===0?'●':i===6?'●':i===42||i===48?'◆':''}</i>)}</div><ol><li><b>① 현재 차례 확인</b><span>플레이어 색과 말의 방향을 확인합니다.</span></li><li><b>② 명령 조립</b><span>일반 턴은 전진 3번, 더블찬스는 6번입니다.</span></li><li><b>③ 실행 결과 관찰</b><span>회전과 이동을 보고 숨겨진 벽을 기억합니다.</span></li><li><b>④ 수정하고 재도전</b><span>난이도에 따라 충돌 지점 또는 출발점에서 계속합니다.</span></li></ol></div></div>,
  <div className="rule-slide"><span className="slide-kicker">3 / 4 · 교사 운영</span><h2>게임 사전 설정부터 종료까지</h2><div className="teacher-steps"><article><b>1</b><span>플레이어 명단, 경기장 수, 난이도를 설정하고 4자리 학급 코드를 기억합니다.</span></article><article><b>2</b><span>대표 QR 코드 또는 링크를 각 태블릿에서 엽니다.</span></article><article><b>3</b><span>태블릿에서 경기장 번호와 두 플레이어를 차례로 선택합니다.</span></article><article><b>4</b><span>모든 대결이 끝나면 게임 종료를 눌러 최종 순위를 공개합니다.</span></article></div></div>,
  <div className="rule-slide youtube-slide"><span className="slide-kicker">4 / 4 · 더 알아보기</span><div className="youtube-mark">▶</div><h2>원작 규칙이 궁금한가요?</h2><p>유튜브에서 <b>“더 지니어스 기억의 미로 규칙”</b>을 검색해 보세요.</p><button className="primary" onClick={startPractice}>연습 경기 시작</button></div>
];return <div className="modal" role="dialog" aria-modal="true"><section className="rules-modal"><header><div><img src={`${IMG}icon_logo_maze_mark.png`}/><b>기억의 미로 · 게임 방법</b></div><button onClick={close}>✕ 닫기</button></header><div className="rules-body">{slides[slide]}</div><footer><button onClick={()=>setSlide(v=>Math.max(0,v-1))} disabled={slide===0}>← 이전</button><div>{slides.map((_,i)=><button key={i} className={i===slide?'active':''} onClick={()=>setSlide(i)} aria-label={`${i+1}번째 슬라이드`}/>)}</div>{slide<3?<button className="primary" onClick={()=>setSlide(v=>v+1)}>다음 →</button>:<button className="primary" onClick={close}>확인</button>}</footer></section></div>}

export default function Home({go}:{go:(screen:Screen)=>void}){const [rules,setRules]=useState(false);return <main className="home"><nav><div className="brand"><img src={`${IMG}icon_logo_maze_mark.png`}/><b>기억의 미로</b></div><SoundButton/></nav><section className="hero"><div className="hero-copy"><span className="hero-kicker">더 지니어스 한 학급 놀이</span><h1>기억의 미로</h1><p><b>5학년 실과</b> 컴퓨터와 문제해결<br/><b>4학년 수학</b> 평면도형의 이동</p><div className="home-actions"><button className="primary" onClick={()=>go('teacher')}>교사로 시작</button><button className="secondary" onClick={()=>setRules(true)}>게임 방법</button><button className="secondary practice-btn" onClick={()=>go('practice')}>연습 경기</button></div></div></section>{rules&&<RulesModal close={()=>setRules(false)} startPractice={()=>{setRules(false);go('practice')}}/>}</main>}
