import { useState } from 'react';

const IMG='/assets/images/';
export type Screen='home'|'venue'|'practice'|'teacher';

function RulesModal({close,startPractice}:{close:()=>void;startPractice:()=>void}){const [slide,setSlide]=useState(0);const slides=[
  <div className="rule-slide"><span className="slide-kicker">1 / 4 · 게임의 목적</span><h2>숨겨진 벽을 기억하고<br/>먼저 도착하세요</h2><div className="goal-visual"><img src={`${IMG}pawn_player_mint.png`}/><span>명령 조립 → 실행 → 확인 → 수정</span><img src={`${IMG}marker_goa_flag.png`}/></div><p>두 플레이어는 서로 다른 출발점에서 시작합니다. 이동과 회전 명령을 조립해 자신의 색과 같은 도착점에 먼저 닿으면 승리합니다.</p></div>,
  <div className="rule-slide"><span className="slide-kicker">2 / 4 · 실제 게임 방법</span><h2>한 태블릿에서 번갈아 실행해요</h2><div className="how-layout"><div className="tiny-board">{Array.from({length:49},(_,i)=><i key={i}>{i===0?'●':i===6?'●':i===42||i===48?'◆':''}</i>)}</div><ol><li><b>① 현재 차례 확인</b><span>플레이어 색과 말의 방향을 확인합니다.</span></li><li><b>② 명령 조립</b><span>일반 턴은 전진 3번, 더블찬스는 6번입니다.</span></li><li><b>③ 실행 결과 관찰</b><span>회전과 이동을 보고 숨겨진 벽을 기억합니다.</span></li><li><b>④ 수정하고 재도전</b><span>난이도에 따라 충돌 지점 또는 출발점에서 계속합니다.</span></li></ol></div></div>,
  <div className="rule-slide"><span className="slide-kicker">3 / 4 · 교사 운영</span><h2>게임 사전 설정부터 종료까지</h2><div className="teacher-steps"><article><b>1</b><span>플레이어 명단, 경기장 수, 난이도를 설정하고 4자리 학급 코드를 기억합니다.</span></article><article><b>2</b><span>대표 QR 코드 또는 링크를 각 태블릿에서 엽니다.</span></article><article><b>3</b><span>태블릿에서 경기장 번호와 두 플레이어를 차례로 선택합니다.</span></article><article><b>4</b><span>모든 대결이 끝나면 게임 종료를 눌러 최종 순위를 공개합니다.</span></article></div></div>,
  <div className="rule-slide youtube-slide"><span className="slide-kicker">4 / 4 · 더 알아보기</span><div className="youtube-mark">▶</div><h2>원작 규칙이 궁금한가요?</h2><p>유튜브에서 <b>“더 지니어스 기억의 미로 규칙”</b>을 검색해 보세요.</p><button className="primary" onClick={startPractice}>연습 경기 시작</button></div>
];return <div className="modal" role="dialog" aria-modal="true"><section className="rules-modal"><header><div><img src={`${IMG}icon_logo_maze_mark.png`}/><b>기억의 미로 · 게임 방법</b></div><button onClick={close}>✕ 닫기</button></header><div className="rules-body">{slides[slide]}</div><footer><button onClick={()=>setSlide(v=>Math.max(0,v-1))} disabled={slide===0}>← 이전</button><div>{slides.map((_,i)=><button key={i} className={i===slide?'active':''} onClick={()=>setSlide(i)} aria-label={`${i+1}번째 슬라이드`}/>)}</div>{slide<3?<button className="primary" onClick={()=>setSlide(v=>v+1)}>다음 →</button>:<button className="primary" onClick={close}>확인</button>}</footer></section></div>}

type Course='practical'|'math';
function IntroModal({close,complete}:{close:()=>void;complete:()=>void}){const [course,setCourse]=useState<Course|null>(null),[slide,setSlide]=useState(0),[answer,setAnswer]=useState('');const practical=[
  <div className="lesson-slide"><span>5학년 실과 · 개념 1</span><h2>문제에는 현재 상태와<br/>목표 상태가 있어요</h2><div className="state-flow"><b>현재 상태<br/><small>출발점에 있는 말</small></b><i>→ 해결 방법 →</i><b>목표 상태<br/><small>도착점에 도착한 말</small></b></div><p>문제 속 요소를 찾고, 현재 상태를 목표 상태로 바꾸는 방법을 작은 부분으로 나누어 생각합니다.</p></div>,
  <div className="lesson-slide"><span>5학년 실과 · 개념 2</span><h2>알고리즘은 문제 해결 방법을<br/>순서대로 표현한 것이에요</h2><div className="algorithm-chain"><b>앞으로 1칸</b><b>오른쪽 90°</b><b>앞으로 1칸</b><b>실행하고 확인</b></div><p>명령은 명확한 순서로 실행됩니다. 결과가 예상과 다르면 어느 명령에서 문제가 생겼는지 찾아 순서를 고쳐 보세요.</p></div>,
  <Quiz key="pq" question="오른쪽을 보는 말에게 ‘앞으로 → 왼쪽 회전 → 앞으로’를 실행하면 마지막에는 어느 방향을 볼까요?" choices={['오른쪽','위쪽','아래쪽']} correct="위쪽" answer={answer} setAnswer={setAnswer}/>
];const math=[
  <div className="lesson-slide"><span>4학년 수학 · 개념 1</span><h2>점의 이동은 위치와 방향으로<br/>정확하게 설명해요</h2><div className="grid-demo"><b>출발 ●</b><i>오른쪽으로 3칸 →</i><b>● 도착</b></div><p>격자에서 점은 위, 아래, 오른쪽, 왼쪽으로 몇 칸 이동했는지 설명할 수 있습니다. 게임의 ‘앞으로 1칸’도 현재 방향을 기준으로 한 점의 이동입니다.</p></div>,
  <div className="lesson-slide"><span>4학년 수학 · 개념 2</span><h2>돌리면 위치는 그대로,<br/>방향이 달라져요</h2><div className="turn-demo"><b>↑</b><i>시계 방향 90°</i><b>→</b><i>시계 반대 방향 90°</i><b>↑</b></div><p>게임의 오른쪽·왼쪽 회전은 말을 90° 돌리는 명령입니다. 회전할 때에는 칸을 옮기지 않고 바라보는 방향만 바뀝니다.</p></div>,
  <Quiz key="mq" question="오른쪽을 보는 말이 앞으로 2칸, 왼쪽으로 90° 회전, 앞으로 1칸 움직였습니다. 마지막 방향은?" choices={['위쪽','오른쪽','왼쪽']} correct="위쪽" answer={answer} setAnswer={setAnswer}/>
];const slides=course==='practical'?practical:math;return <div className="modal intro-backdrop" role="dialog" aria-modal="true"><section className="intro-modal"><header><div><img src={`${IMG}icon_logo_maze_mark.png`}/><b>게임 전 교과 개념 열기</b></div><button onClick={close}>✕ 닫기</button></header>{!course?<div className="course-choice"><span>어떤 교과와 연결해서 시작할까요?</span><h2>오늘 수업을 선택하세요</h2><div><button className="practical" onClick={()=>setCourse('practical')}><small>5학년</small><b>실과</b><em>컴퓨터와 문제 해결</em></button><button className="math" onClick={()=>setCourse('math')}><small>4학년</small><b>수학</b><em>평면도형의 이동</em></button></div></div>:<><div className="intro-body">{slides[slide]}</div><footer><button onClick={()=>{setAnswer('');if(slide===0)setCourse(null);else setSlide(v=>v-1)}}>← 이전</button><span>{slide+1} / 3</span>{slide<2?<button className="primary" onClick={()=>{setAnswer('');setSlide(v=>v+1)}}>다음 →</button>:<button className="primary" disabled={!answer} onClick={complete}>개념 학습 완료</button>}</footer></>}</section></div>}

function Quiz({question,choices,correct,answer,setAnswer}:{question:string;choices:string[];correct:string;answer:string;setAnswer:(value:string)=>void}){return <div className="lesson-slide quiz-slide"><span>확인 문제</span><h2>{question}</h2><div className="quiz-choices">{choices.map(choice=><button key={choice} className={answer===choice?(choice===correct?'correct':'wrong'):''} onClick={()=>setAnswer(choice)}>{choice}</button>)}</div>{answer&&<p className={answer===correct?'quiz-feedback correct':'quiz-feedback'}>{answer===correct?'정답입니다! 위치와 방향을 잘 구분했어요.':`다시 생각해 볼까요? 정답은 ${correct}입니다.`}</p>}</div>}

export default function Home({go}:{go:(screen:Screen)=>void}){const [rules,setRules]=useState(false),[intro,setIntro]=useState(false);return <main className="home"><nav><div className="brand"><img src={`${IMG}icon_logo_maze_mark.png`}/><b>기억의 미로</b></div></nav><section className="hero"><div className="hero-copy"><span className="hero-kicker">더 지니어스 한 학급 놀이</span><h1>기억의 미로</h1><p><b>5학년 실과</b> 컴퓨터와 문제해결<br/><b>4학년 수학</b> 평면도형의 이동</p><div className="home-actions"><button className="primary" onClick={()=>setIntro(true)}>교사로 시작</button><button className="secondary" onClick={()=>setRules(true)}>게임 방법</button><button className="secondary practice-btn" onClick={()=>go('practice')}>연습 경기</button></div></div></section>{rules&&<RulesModal close={()=>setRules(false)} startPractice={()=>{setRules(false);go('practice')}}/>}{intro&&<IntroModal close={()=>setIntro(false)} complete={()=>go('teacher')}/>}</main>}
