import { useEffect, useMemo, useState } from 'react';
import Peer from 'peerjs';
import QRCode from 'qrcode';
import { makeId, rankStudents } from './game';
import type { ClassSession, Difficulty, MatchResult } from './types';

const IMG='/assets/images/';
const SESSION_KEY='memory-maze:teacher-game:v4';
type VenueStatus='waiting'|'connected'|'available'|'occupied'|'result_pending'|'closed';
type TeacherGame=ClassSession&{venueCount:number;difficulty:Difficulty;statuses:Record<number,VenueStatus>;ended:boolean};
type VenueEvent={type:'connected'|'occupied'|'available'|'result';venue:number;result?:MatchResult};
const readTeacher=():TeacherGame|null=>{try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}};
const clearMemoryMazeData=()=>{for(let index=localStorage.length-1;index>=0;index--){const key=localStorage.key(index);if(key?.startsWith('memory-maze:'))localStorage.removeItem(key)}};

function AccessCard({game}:{game:TeacherGame}){
  const [qr,setQr]=useState(''),[expanded,setExpanded]=useState(false),[copied,setCopied]=useState(false);
  const url=useMemo(()=>{const target=new URL(location.href);target.search='';target.searchParams.set('lobby','1');target.searchParams.set('class',game.code);target.searchParams.set('venues',String(game.venueCount));target.searchParams.set('difficulty',game.difficulty);target.searchParams.set('players',btoa(unescape(encodeURIComponent(JSON.stringify(game.students.map(s=>s.name))))));return target.toString()},[game]);
  useEffect(()=>{QRCode.toDataURL(url,{width:260,margin:1,color:{dark:'#26233c',light:'#fffdf7'}}).then(setQr)},[url]);
  const copy=async()=>{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),2200)};
  return <div className="access-panel"><div className="access-qr">{qr&&<button className="qr-trigger" onClick={()=>setExpanded(true)} aria-label="대표 접속 QR 크게 보기"><img src={qr}/><span>클릭해서 크게 보기</span></button>}<div><h3>대표 접속 QR</h3><p>모든 태블릿에서 같은 QR 또는 링크를 사용합니다.</p><div className="copy-row"><button className={copied?'copied':''} onClick={()=>void copy()}>대표 링크 복사</button>{copied&&<strong role="status">✓ 링크가 복사되었습니다.</strong>}</div></div></div><p className="selection-help">태블릿에서 경기장 번호는 선생님이 직접 지정해 주세요.</p>{expanded&&<div className="modal qr-modal" onClick={()=>setExpanded(false)}><section onClick={event=>event.stopPropagation()}><button className="qr-close" onClick={()=>setExpanded(false)}>✕ 닫기</button><h2>경기장 접속 QR</h2><img src={qr}/><p>태블릿 카메라로 QR 코드를 인식하세요.</p></section></div>}</div>;
}

const STATUS_LABEL:Record<VenueStatus,string>={waiting:'미접속',connected:'접속됨',available:'이용 가능',occupied:'경기 중',result_pending:'결과 전송 중',closed:'종료'};

export default function Teacher({goHome}:{goHome:()=>void}){
  const [game,setGame]=useState<TeacherGame|null>(readTeacher),[names,setNames]=useState('홍길동\n임꺽정\n심청이\n흥부'),[venues,setVenues]=useState('2'),[difficulty,setDifficulty]=useState<Difficulty>('easy'),[recover,setRecover]=useState(''),[confirm,setConfirm]=useState(false),[final,setFinal]=useState(false),[setupError,setSetupError]=useState('');
  const students=useMemo(()=>names.split(/[\n,]/).map(n=>n.trim()).filter(Boolean).map((name,i)=>({id:`student-${i}`,name})),[names]);
  const save=(next:TeacherGame)=>{localStorage.setItem(SESSION_KEY,JSON.stringify(next));setGame(next)};

  useEffect(()=>{if(!game||game.ended)return;const peer=new Peer(`memory-maze-class-${game.code}`);peer.on('connection',conn=>conn.on('data',data=>{const event=data as VenueEvent,current=readTeacher()||game;let results=current.results;if(event.type==='result'&&event.result&&!results.some(item=>item.matchId===event.result?.matchId))results=[...results,{...event.result,venueNumber:event.venue}];const status:VenueStatus=event.type==='connected'?'connected':event.type==='occupied'?'occupied':event.type==='available'||event.type==='result'?'available':current.statuses[event.venue];save({...current,results,statuses:{...current.statuses,[event.venue]:status}});conn.send({ok:true})}));return()=>peer.destroy()},[game?.code,game?.ended]);

  const create=()=>{const count=Number(venues);if(!venues||!Number.isInteger(count)||count<1){setSetupError('운영할 경기장 수를 1부터 15 사이의 숫자로 입력해 주세요.');return}if(count>15){setSetupError('운영할 경기장 수의 최대 숫자는 15까지입니다. 다른 숫자를 입력해 주세요.');return}const code=String(Math.floor(1000+Math.random()*9000)),statuses=Object.fromEntries(Array.from({length:count},(_,i)=>[i+1,'waiting'])) as Record<number,VenueStatus>;save({id:makeId('class'),code,className:'기억의 미로',students,results:[],createdAt:Date.now(),venueCount:count,difficulty,statuses,ended:false})};
  const ranking=game?rankStudents(game):[];
  const report=()=>['순위\t이름\t경기\t승\t무\t패\t승점\t승률\t평균 턴\t평균 충돌',...ranking.map((r,i)=>`${i+1}\t${r.name}\t${r.games}\t${r.wins}\t${r.draws}\t${r.losses}\t${r.points}\t${Math.round(r.winRate*100)}%\t${r.averageTurns.toFixed(1)}\t${r.averageHits.toFixed(1)}`)].join('\n');
  const notifyVenues=(type:'game-ended'|'game-reset')=>{if(!game)return;for(let venue=1;venue<=game.venueCount;venue++){const peer=new Peer();peer.on('open',()=>{const conn=peer.connect(`memory-maze-venue-${game.code}-${venue}`);conn.on('open',()=>{conn.send({type});setTimeout(()=>peer.destroy(),250)})});setTimeout(()=>peer.destroy(),3000)}};
  const resetGame=()=>{notifyVenues('game-reset');clearMemoryMazeData();dispatchEvent(new Event('memory-maze:main-bgm'));setGame(null);setFinal(false);goHome()};
  const finish=()=>{if(!game)return;const next={...game,ended:true,statuses:Object.fromEntries(Object.keys(game.statuses).map(k=>[k,'closed'])) as Record<number,VenueStatus>};save(next);setConfirm(false);setFinal(true);dispatchEvent(new Event('memory-maze:result-bgm'));notifyVenues('game-ended')};

  if(final&&game)return <main className="final-ranking"><div className="trophy-celebration"><img className="confetti" src={`${IMG}effect_goal_confetti.png`}/><img className="trophy" src={`${IMG}icon_victory_trophy.png`}/><i>★</i><i>✦</i><i>★</i></div><span>전체 게임 종료</span><h1>최종 순위</h1><div className="podium">{ranking.slice(0,3).map((r,i)=><article key={r.id} className={`rank-${i+1}`}><b>{i+1}위</b><h2>{r.name}</h2><p>{r.points}점 · {r.wins}승 · {r.draws}무</p></article>)}</div><div className="final-actions"><button className="primary" onClick={()=>void navigator.clipboard.writeText(report())}>게임 결과 복사하기</button><button className="secondary" onClick={resetGame}>메인화면 (게임 초기화)</button></div><p>게임 초기화 시 이 기기에 저장된 플레이어 명단과 모든 경기 전적이 삭제됩니다.</p><p>결과 복사 버튼을 누른 뒤 한셀 또는 엑셀에서 붙여넣으면 표로 저장할 수 있습니다.</p></main>;

  if(!game)return <main className="teacher"><header><button className="logo-button" onClick={goHome}><img src={`${IMG}icon_logo_maze_mark.png`}/></button><div><span>교사 운영 페이지</span><h1>게임 사전 설정</h1></div></header><section className="teacher-setup setup-wide"><div className="setup-main"><h2>게임 사전 설정</h2><label>플레이어 명단 <small>줄바꿈 또는 쉼표로 구분 · {students.length}명</small><textarea value={names} onChange={e=>setNames(e.target.value)}/></label><div className="field-group"><div className="field-head"><b>운영할 경기장 수</b><small>2명의 플레이어가 하나의 경기장을 이용합니다. 전체 플레이어 수의 절반으로 경기장을 만들어 주세요.</small></div><input inputMode="numeric" value={venues} onChange={e=>setVenues(e.target.value.replace(/\D/g,''))}/><small>운영할 경기장 수는 최대 15개입니다.</small></div><fieldset className="difficulty-field"><legend>난이도</legend><div><button className={difficulty==='easy'?'active':''} onClick={()=>setDifficulty('easy')}>쉬움</button><button className={difficulty==='hard'?'active':''} onClick={()=>setDifficulty('hard')}>어려움</button></div><p>{difficulty==='easy'?'말이 벽에 부딪혔을 때 출발점으로 되돌아 오지 않습니다. 벽에 부딪힌 자리에서 게임을 계속합니다.':'말이 벽에 부딪힐 경우 출발점으로 복귀하여 다시 시작합니다.'}{difficulty==='hard'&&<strong className="genius-rule">실제 지니어스 게임의 규칙과 동일한 규칙입니다.</strong>}</p></fieldset></div><aside className="setup-actions"><div><span>설정이 끝났나요?</span><h2>{students.length}명의 플레이어와<br/>{venues||0}개의 경기장</h2><p>게임을 만들면 4자리 학급 코드와 태블릿 접속 QR이 생성됩니다.</p><button className="primary create-game" disabled={students.length<2||new Set(students.map(s=>s.name)).size!==students.length} onClick={create}>게임 만들기 →</button></div><div className="recover"><b>기존 게임 복구</b><p>교사 운영 페이지를 나갔다면 학급 코드로 다시 접속하세요.</p><div><input inputMode="numeric" maxLength={4} placeholder="4자리 학급 코드" value={recover} onChange={e=>setRecover(e.target.value.replace(/\D/g,'').slice(0,4))}/><button onClick={()=>{const saved=readTeacher();if(saved?.code===recover)setGame(saved)}}>재접속</button></div></div></aside></section>{setupError&&<div className="modal"><section className="confirm"><h2>경기장 수를 확인해 주세요</h2><p>{setupError}</p><div><button className="primary" onClick={()=>setSetupError('')}>확인</button></div></section></div>}</main>;

  return <main className="teacher">
    <header><button className="logo-button" onClick={goHome}><img src={`${IMG}icon_logo_maze_mark.png`}/></button><div><span>교사 운영 페이지</span><h1>기억의 미로 게임</h1></div><div className="teacher-header-actions"><button className="secondary reset-btn" onClick={resetGame}>게임 초기화(메인화면)</button><button className="reveal-btn" onClick={()=>setConfirm(true)}>게임 종료(결과 공개)</button></div></header>
    <section className="class-code"><div><span>학급 코드</span><strong>{game.code}</strong></div><p>학급 코드를 기억해 주세요. 혹시라도 교사 운영 페이지에서 나갔을 경우 학급 코드를 입력하시면 재접속하실 수 있습니다.</p></section>
    <div className="teacher-grid">
      <section><header><h2>경기장 접속</h2><span>{game.venueCount}개 운영 · {game.difficulty==='easy'?'쉬움':'어려움'}</span></header><AccessCard game={game}/><div className="venue-status-grid">{Array.from({length:game.venueCount},(_,i)=>{const status=game.statuses[i+1]||'waiting';return <article key={i}><b>{i+1}번 경기장</b><small className={status}>{STATUS_LABEL[status]}</small></article>})}</div></section>
      <section><header><h2>현재 순위</h2><span>{game.results.length}경기 완료</span></header><table><thead><tr><th>순위</th><th>이름</th><th>경기</th><th>승</th><th>무</th><th>승점</th></tr></thead><tbody>{ranking.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.name}</td><td>{r.games}</td><td>{r.wins}</td><td>{r.draws}</td><td>{r.points}</td></tr>)}</tbody></table>
        <div className="game-logs"><h3>경기 로그</h3>{game.results.length?game.results.slice().reverse().map(result=>{const winner=result.winnerId?result.playerNames[result.winnerId]:null,totalTurns=Object.values(result.turnsByPlayer).reduce((sum,value)=>sum+value,0);return <article key={result.matchId}><b>{result.venueNumber||'-'}번 경기장</b><span>{result.playerNames[result.playerAId]} vs {result.playerNames[result.playerBId]} · {totalTurns}턴</span><strong>{winner?`${winner} 승리`:'무승부'}</strong></article>}):<p>완료된 경기 결과가 여기에 표시됩니다.</p>}</div>
      </section>
    </div>
    {confirm&&<div className="modal"><section className="confirm"><h2>전체 경기를 종료하시겠습니까?</h2><p>운영 중인 게임은 전적에 반영되지 않습니다.</p><div><button onClick={()=>setConfirm(false)}>취소</button><button className="danger-btn" onClick={finish}>확인하고 종료</button></div></section></div>}
  </main>;
}
